version: 2.1

jobs:
  danger:
    docker:
      - image: jkkitakita/circleci-danger # https://github.com/jkkitakita/circleci-danger
    resource_class: small
    steps:
      - checkout
      # - run: sh run-danger.sh $ENV_GITHUB_API_TOKEN $ENV_GITHUB_PULL_REQUEST_URL
      - run: export DANGER_GITHUB_API_TOKEN=$ENV_GITHUB_API_TOKEN
      - run: bundle exec danger --fail-on-errors=true

workflows:
  version: 2.1
  danger:
    jobs:
      - danger
