version: 2.1

executors:
  ios-executor:
    macos:
      xcode: 13.4.1
    resource_class: medium

jobs:
  setup-mint:
    executor: ios-executor
    environment:
      MINT_VERSION: 0.17.0
    steps:
      - run: curl -Ls -o mint.zip https://github.com/yonaskolb/Mint/releases/download/${MINT_VERSION}/mint.zip
      - run: unzip mint.zip; rm mint.zip
      - run: mv mint /usr/local/bin/
  build:
    executor: ios-executor
    steps:
      - run: mint version
      #- checkout
      #- run: bundle install
      #- run: bundle exec danger --fail-on-errors=true

workflows:
  version: 2
  pullrequest:
    jobs:
      - setup-mint
      - build:
          requires:
            - setup-mint
