version: 2.1

jobs:
  danger:
    docker:
      - image: jkkitakita/circleci-danger # https://github.com/jkkitakita/circleci-danger
    resource_class: small
    steps:
      - checkout
      - run: echo "==== RUN ===="
      - run: echo $ENV_CIRCLE_CI_TEST
      # - run: sh run-danger.sh
      - run: echo "==== END ===="

workflows:
  version: 2.1
  danger:
    jobs:
      - danger
