version: 2.1

jobs:
  danger:
    docker:
      - image: jkkitakita/circleci-danger # https://github.com/jkkitakita/circleci-danger
    resource_class: small
    steps:
      - checkout
      - run: bundle exec danger --fail-on-errors=true

workflows:
  version: 2.1
  danger:
    jobs:
      - danger
