# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :run_all_tests do
    # add actions here: https://docs.fastlane.tools/actions
    run_tests(
      devices: ["iPhone 13"]
    )
  end

  lane :run_danger do
    danger(
      danger_id: "unit-tests",
      dangerfile: "./Dangerfile",
      github_api_token: ENV["GITHUB_API_TOKEN"],
      pr: ENV["GITHUB_PULL_REQUEST_URL"],
      verbose: true,
      fail_on_errors: true
    )
  end
end
